# Generated by Django 4.2 on 2023-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_variationcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombinations',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
