# Generated by Django 4.2 on 2023-04-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_variationcombinations_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcombinations',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
            preserve_default=False,
        ),
    ]
