# Generated by Django 4.2 on 2023-04-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_variationtypes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.RemoveField(
            model_name='variationvalues',
            name='VariationType',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_type',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
        migrations.DeleteModel(
            name='VariationTypes',
        ),
        migrations.DeleteModel(
            name='VariationValues',
        ),
        migrations.AddField(
            model_name='variation',
            name='colour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.colours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.sizes'),
            preserve_default=False,
        ),
    ]
